global:
    resolve_timeout: 1m
    smtp_smarthost: 'smtp.qq.com:465'
    smtp_from: 'ikubernetes@qq.com'
    smtp_auth_username: 'ikubernetes@qq.com'
    smtp_auth_password: 'egnvzqffqjsjcaec'
    smtp_hello: '@qq.com'
    smtp_require_tls: false

route:
    group_by: ['group', 'job', 'alertname'] 
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 10m

    receiver: email
    #receiver: wechat

templates:
  - '/etc/alertmanager/email_template.tmpl'

 # 定义接收者
receivers:
- name: 'email'
  email_configs:
    - to: 'mage@magedu.com'
      headers:
        subject: "{{ .Status | toUpper }} {{ .CommonLabels.env }}:{{ .CommonLabels.cluster }} {{ .CommonLabels.alertname }}"
      html: '{{ template "email.to.html" . }}'
      send_resolved: true 

- name: 'wechat'
  wechat_configs:
    - corp_id: ww4c893118fbf4d07c 
      to_user: '@all'
      agent_id: 1000008
      api_secret: WTepmmaqxbBOeTQOuxa0Olzov_hSEWsZWrPX1k6opMk
      send_resolved: true

inhibit_rules: 
  - source_match: 
     severity: 'critical' 
    target_match: 
     severity: 'warning' 
    equal: ['alertname', 'instance']
